give @s written_book[written_book_content={pages:[\
    '["",{"text":"0 前言","bold":true},{"text":"\\n\\n《导弹战争：融合版》是对Cubehamster等人在1.8时代的作品《导弹战争》的复刻。该复刻版在原作的基础上加入了新设置、新导弹以及融合机制。\\n\\n游戏详解共分为玩法概要、规则详解、道具介绍、导弹技术参数详解和指令集等部分。"}]',\
    '["",{"text":"初涉此小游戏，仅需阅读“玩法概要”和“道具介绍”即可。","color":"black"}]',\
    '["",{"text":"1 玩法概要","bold":true},{"text":"\\n\\n使用/","color":"black"},{"text":"trigger","color":"light_purple"},{"text":" menu","color":"blue"},{"text":"调出菜单，可以从此面板中开始游戏。\\n游戏开始后，双方会定期得到随机道具，包括防御性道具和用于部署导弹的怪物蛋。\\n\\n持怪物蛋在平台前端的地面上右键即可在前下方部署相应导弹，使用防御性道具可以摧毁或阻拦敌方导弹。","color":"black"}]',\
    '["",{"text":"用导弹破坏对方平台并摧毁对方地狱门即可获胜。\\n\\n《导弹战争：融合版》新增多种融合导弹和融合道具，某些导弹刷怪蛋两两组合可合成新的导弹，防御性道具两两组合可以产生新的道具。\\n\\n"},{"text":"（具体方法见“道具介绍”章节）","color":"dark_gray"}]',\
    '[{"text":"皇室模式提供全新的选卡系统，玩家可以选择8种不同的道具出战，消耗费用来使用道具。皇室模式通过依次点击"},{"text":"菜单","color":"dark_green"},{"text":"->"},{"text":"游戏设置","color":"dark_green"},{"text":"->"},{"text":"游戏模式","color":"light_purple"},{"text":"->"},{"text":"皇室","color":"gold"},{"text":"来选中。\\n\\n在此模式下，开始游戏并重置场地后，玩家通过把背包中的道具放至快捷栏中选卡，选卡结束后使用"},{"text":"/","color":"dark_gray"},{"text":"trigger","color":"light_purple"},{"text":" "},{"text":"ready","color":"aqua"},{"text":"，当所有玩家都准备就绪时游戏开始。\\n "}]',\
    '["",{"text":"2 道具介绍","bold":true},{"text":"\\n\\n","color":"black"},{"text":"2.1 防御性道具介绍","color":"dark_green"},{"text":"\\n\\n","color":"black"},{"text":"2.1.1 基础道具","color":"gray"},{"text":"\\n\\n","color":"black"},{"text":"盾（雪球）：","color":"light_purple"},{"text":"投掷后1s在原地生成盾牌；在此改版中，投掷后撞击方块可立即原地生成盾牌。\\n","color":"black"},{"text":"火球（烈焰人刷怪弹）：","color":"light_purple"},{"text":"右键地面原地召唤火球，瞄准敌方导弹敲击火球即可将其发射。\\n","color":"black"}]',\
    '[{"text":"箭矢：","color":"light_purple"},{"text":"配合玩家已有的火矢弓可发射火箭，用于引燃敌方导弹的TNT以进行拦截。","color":"black"}]',\
    '["",{"text":"2.1.2 融合道具","color":"gray"},{"text":"\\n\\n","color":"black"},{"text":"爆裂光灵箭","color":"light_purple"},{"text":"（","color":"black"},{"text":"火球","color":"light_purple"},{"text":"+","color":"black"},{"text":"箭矢","color":"light_purple"},{"text":"）：发射后击中方块即产生爆炸，在敌方平台附近无效。\\n","color":"black"},{"text":"平台三叉戟","color":"light_purple"},{"text":"（","color":"black"},{"text":"箭矢","color":"light_purple"},{"text":"+","color":"black"},{"text":"盾","color":"light_purple"},{"text":"）：发射后击中方块则在原地生成平台，在敌方地狱门附近无效。\\n","color":"black"},{"text":"末影珍珠","color":"light_purple"},{"text":"（","color":"black"},{"text":"火球","color":"light_purple"},{"text":"+","color":"black"},{"text":"盾","color":"light_purple"},{"text":"）：发射以传送到导弹上，无法直接传送到敌方平台上。","color":"black"}]',\
    '[{"text":"防御性道具在皇室模式的费用如下表。\\n\\n道具　　  费用\\n"},{"text":"盾","color":"light_purple"},{"text":"　　　  "},{"text":"3","color":"dark_green"},{"text":"\\n"},{"text":"火球","color":"light_purple"},{"text":"　　  "},{"text":"4","color":"dark_green"},{"text":"\\n箭　　　  "},{"text":"1","color":"dark_green"},{"text":"\\n"},{"text":"光灵箭","color":"light_purple"},{"text":"　  "},{"text":"5","color":"dark_green"},{"text":"\\n"},{"text":"三叉戟","color":"light_purple"},{"text":"　  "},{"text":"4","color":"dark_green"},{"text":"\\n"},{"text":"末影珍珠","color":"light_purple"},{"text":"  "},{"text":"2","color":"dark_green"},{"text":"\\n "}]',\
    '["",{"text":"2.2 导弹介绍","color":"dark_green"},{"text":"\\n\\n","color":"black"},{"text":"2.2.1 基础导弹","color":"gray"},{"text":"\\n\\n《导弹战争》原版即具有的五种导弹，在此做了汉化处理。\\n\\n","color":"black"},{"text":"娄金狗","color":"dark_aqua"},{"text":"（","color":"black"},{"text":"Guardian","color":"dark_aqua"},{"text":"，护卫）：弹药少，难以被火球箭矢摧毁。\\n","color":"black"},{"text":"箕水豹","color":"dark_aqua"},{"text":"（","color":"black"},{"text":"Lightning","color":"dark_aqua"},{"text":"，闪电）：移速极快，但脆弱且遇盾则哑火。","color":"black"}]',\
    '["",{"text":"氐土貉","color":"dark_aqua"},{"text":"（","color":"black"},{"text":"Shield buster","color":"dark_aqua"},{"text":"，破盾者）：可穿过一层盾牌，弹身长。\\n","color":"black"},{"text":"奎木狼","color":"dark_aqua"},{"text":"（","color":"black"},{"text":"Tomahawk","color":"dark_aqua"},{"text":"，战斧）：弹药前置，截面纤细。\\n","color":"black"},{"text":"尾火虎","color":"dark_aqua"},{"text":"（","color":"black"},{"text":"Juggernaut","color":"dark_aqua"},{"text":"，霸主）：弹药量大，体积大。\\n\\n","color":"black"},{"text":"2.2.2 融合导弹","color":"gray"},{"text":"\\n\\n融合导弹可通过两种特定的基础导弹合成而来，合成方式如下表。","color":"black"}]',\
    '["",{"text":"　","color":"#333333"},{"text":" 金","color":"black"},{"text":"　","color":"#333333"},{"text":"木","color":"black"},{"text":"　","color":"#333333"},{"text":"水","color":"black"},{"text":"　","color":"#333333"},{"text":"火","color":"black"},{"text":"　","color":"#333333"},{"text":"土\\n金 ","color":"black"},{"text":"无　无　暂无","color":"gray"},{"text":"沙皇","color":"dark_purple"},{"text":"柄雷","color":"light_purple"},{"text":"\\n木 ","color":"black"},{"text":"　　","color":"#333333"},{"text":"无　","color":"gray"},{"text":"匕首","color":"dark_purple"},{"text":"暂无","color":"gray"},{"text":"炎狱","color":"dark_purple"},{"text":"\\n水 ","color":"black"},{"text":"　　　　","color":"#333333"},{"text":"无　","color":"gray"},{"text":"东风","color":"dark_purple"},{"text":"暂无","color":"gray"},{"text":"\\n火 ","color":"black"},{"text":"　　　　　　","color":"#333333"},{"text":"无　暂无","color":"gray"},{"text":"\\n土 ","color":"black"},{"text":"　　　　　　　　","color":"#333333"},{"text":"无","color":"gray"},\
    \
    {"text":"\\n\\n注：","color":"black"},{"text":"暂无","color":"gray"},{"text":"代表今后可能加入\\n\\n融合导弹会具备两种基础导弹的特征。","color":"black"}]',\
    '["",{"text":"沙皇","color":"dark_aqua"},{"text":"（","color":"black"},{"text":"Tsar","color":"dark_aqua"},{"text":"）：极其坚固的核弹，其内部的TNT矿车威胁极大。\\n","color":"black"},{"text":"柄雷","color":"dark_aqua"},{"text":"（","color":"black"},{"text":"Stielhandgranate","color":"dark_aqua"},{"text":"）：极其坚固的破盾者。\\n","color":"black"},{"text":"炎狱","color":"dark_aqua"},{"text":"（","color":"black"},{"text":"Hellfire","color":"dark_aqua"},{"text":"）：截面纤细的破盾导弹。\\n","color":"black"},{"text":"东风","color":"dark_aqua"},{"text":"（","color":"black"},{"text":"Dongfeng","color":"dark_aqua"},{"text":"）：移速极快的高爆导弹。\\n","color":"black"},{"text":"匕首","color":"dark_aqua"},{"text":"（","color":"black"},{"text":"Kinzhal","color":"dark_aqua"},{"text":"）：移速极快的纤细导弹。\\n","color":"black"} ]',\
    '[{"text": "2.2.3 特种导弹\\n", "color": "gray"}, {"text": "\\n特种导弹行使特殊职能。\\n\\n", "color": "black"}, {"text": "天启", "color": "light_purple"}, {"text": "（", "color": "black"}, {"text": "Apocalypse", "color": "light_purple"}, {"text": "）：高抛投弹，专克低位导弹。\\n", "color": "black"}, {"text": "仪凤", "color": "light_purple"}, {"text": "（", "color": "black"}, {"text": "Phoenix", "color": "light_purple"}, {"text": "）：水平投弹，远射程盾构，克平位导弹。\\n", "color": "black"}, {"text": "铺路机", "color": "light_purple"}, {"text": "（", "color": "black"}, {"text": "Paver", "color": "light_purple"}, {"text": "）：无引信，缓慢铺设单向跑酷通道。", "color": "black"}]',\
    '[{"text":"导弹的费用如下表。\\n\\n导弹　    费用\\n"},{"text":"娄金狗    ","color":"dark_aqua"},{"text":"2","color":"dark_green"},{"text":"\\n"},{"text":"箕水豹    ","color":"dark_aqua"},{"text":"3","color":"dark_green"},{"text":"\\n"},{"text":"氐土貉    ","color":"dark_aqua"},{"text":"4","color":"dark_green"},{"text":"\\n"},{"text":"奎木狼    ","color":"dark_aqua"},{"text":"3","color":"dark_green"},{"text":"\\n"},{"text":"尾火虎    ","color":"dark_aqua"},{"text":"4","color":"dark_green"},{"text":"\\n"},{"text":"沙皇　    ","color":"dark_aqua"},{"text":"5","color":"dark_green"},{"text":"\\n"},{"text":"柄雷　    ","color":"dark_aqua"},{"text":"6","color":"dark_green"},{"text":"\\n"},{"text":"炎狱　    ","color":"dark_aqua"},{"text":"3","color":"dark_green"},{"text":"\\n"},{"text":"东风　    ","color":"dark_aqua"},{"text":"5","color":"dark_green"},{"text":"\\n"},{"text":"匕首　    ","color":"dark_aqua"},{"text":"4","color":"dark_green"},{"text":"\\n"}]',\
    '[{"text": "导弹　    费用\\n"}, {"text": "天启　    7\\n仪凤　    9\\n铺路机    3", "color": "light_purple"}]',\
    '["",{"text":"3 规则详解","bold":true},{"text":"\\n\\n","color":"black"},{"text":"3.1 组队规则","color":"dark_green"},{"text":"\\n\\n","color":"black"},{"text":"随机组队：","color":"gold"},{"text":"在游戏开始时，玩家被随机分配到绿队和黄队，当玩家人数为奇数时，其中一队会多一人。人数少的队伍回费或补给会加速。\\n","color":"black"},{"text":"手动组队：","color":"gold"},{"text":"游戏开始前玩家通过组队界面手动组队，无人组队时游戏无法开始，游戏开始时未组队的玩家将观战。","color":"black"}]',\
    '["",{"text":"3.2 游戏规则","color":"dark_green"},{"text":"\\n\\n","color":"black"},{"text":"3.2.1 多元规则","color":"gray"},{"text":"\\n\\n","color":"black"},{"text":"游戏模式","bold":true},{"text":"\\n","color":"black"},{"text":"普通：","color":"light_purple"},{"text":"无特性，所有规则均可调节。\\n","color":"black"},{"text":"分钟：","color":"light_purple"},{"text":"补给时间固定为60s，即每分钟得到所有基础导弹和防御性道具，此模式下不可禁用防御性道具。\\n","color":"black"}]',\
    '[{"text":"皇室：","color":"light_purple"},{"text":"在此模式下补给时间和箭矢数量将不可用，不可禁用防御性道具，玩家游戏开始前自选卡组并通过在游戏中消耗费用部署道具以作战。","color": "black"}]',\
    '["",{"text":"行动增益","bold":true},{"text":"\\n","color":"black"},{"text":"普通移速：","color":"light_purple"},{"text":"不会获得速度或跳跃提升效果。\\n","color":"black"},{"text":"神行太保：","color":"light_purple"},{"text":"获得速度I和跳跃提升II。\\n","color":"black"},{"text":"齐天大圣：","color":"light_purple"},{"text":"获得速度IV和跳跃提升VI。\\n\\n","color":"black"},{"text":"平台材料","bold":true},{"text":"\\n更改双方的平台材料，五个可选项按抗爆炸性排列为：\\n","color":"black"},{"text":"玻璃、羊毛、带釉陶瓦、混凝土、陶瓦。","color":"light_purple"}]',\
    '["",{"text":"3.2.2 二元规则","color":"gray"},{"text":"\\n\\n","color":"black"},{"text":"死亡掉落：","color":"gold"},{"text":"禁用则开启死亡不掉落，但玩家每次重生后都会获得弓，皇室模式下卡牌在回费时刷新。\\n","color":"black"},{"text":"破坏方块：","color":"gold"},{"text":"启用则可以手动拆除敌方导弹和盾等。\\n","color":"black"},{"text":"防御道具：","color":"gold"},{"text":"启用则补给盾、火球、箭矢三种基础防御性道具。\\n"},{"text": "火球防御：","color": "gold"},{"text":"禁用则火球会在地狱门前爆炸，启用则火球无法摧毁地狱门。\\n ","color":"black"}]',\
    '["",{"text":"部署位置：","color":"gold"},{"text":"“平台”意味着我方导弹仅可在我方平台附近部署，其他位置部署只会消耗怪物蛋；“全局”意味着双方导弹可以在任意位置部署。\\n","color":"black"},{"text":"道具上限：","color":"gold"},{"text":"双方均会定期得到道具补给，启用则补给时不会获得已有的道具。\\n","color":"black"},{"text":"反向消退：","color":"gold"},{"text":"启用则消退模式中平台从地狱门侧开始消失。\\n","color":"black"}]',\
    '["",{"text":"3.2.3 数值规则","color":"gray"},{"text":"\\n\\n","color":"black"},{"text":"补给时间：","color":"dark_aqua"},{"text":"双方所有玩家都会定期得到补给，此选项设置补给的周期（皇室模式的回费间隔固定为此周期的一半）。\\n","color":"black"},{"text":"箭矢数量：","color":"dark_aqua"},{"text":"每次补给时有概率获得箭矢，此选项设置每次补给箭矢的数量（若物品上限开启，玩家仅在耗尽箭矢后才能被补给箭矢）。\\n ","color":"black"}]',\
    '["",{"text":"消退时间：","color":"dark_aqua"},{"text":"开启后，双方的玩家以此值为周期逐层消失，在一定时间后，进入补给（回费）速度翻倍的双倍圣水模式。\\n","color":"black"},{"text":"平台距离：","color":"dark_aqua"},{"text":"双方平台之间的空间长度（实际上，此选项设置的是平台距双方中点的距离）。\\n","color":"black"},{"text":"平台厚度：","color":"dark_aqua"},{"text":"双方平台均由厚度相等的三层组成（每层颜色相同），此选项设置单层的厚度。","color":"black"}]',\
    '["",{"text":"4 导弹技术参数详解","bold":true},{"text":"\\n\\n","color":"black"},{"text":"4.1 基础导弹","color":"dark_green"},{"text":"（5）","color":"gray"},{"text":"\\n\\n以下5种导弹作者系原作作者Cubehamster等人。在此复刻版中，除了tomahawk导弹中的陶瓦被置换为玻璃之外，其余均原样复刻。","color":"black"}]',\
    '["",{"text":"名称"},{"text":"　","color":"#333333"},{"text":" 长宽高","color":"black"},{"text":"　","color":"#333333"},{"text":" 弹药量\\n娄金狗 08x3x3 ","color":"black"},{"text":"4","color":"dark_aqua"},{"text":"\\n箕水豹 09x3x2 ","color":"black"},{"text":"10","color":"gold"},{"text":"\\n氐土貉 14x3x3 ","color":"black"},{"text":"17","color":"gold"},{"text":"\\n奎木狼 ","color":"black"},{"text":"12x2x2","color":"black"},{"text":" 14","color":"gold"},{"text":"\\n尾火虎 11x3x3 ","color":"black"},{"text":"22","color":"red"},{"text":"\\n\\n名称","color":"black"},{"text":"　","color":"#333333"},{"text":" 移速","color":"black"},{"text":"　","color":"#333333"},{"text":"  怪物蛋 No\\n娄金狗 1.7m/s 守卫者 1 \\n箕水豹 ","color":"black"},{"text":"3.3m/s","color":"red"},{"text":" 豹猫","color":"black"},{"text":"　","color":"#333333"},{"text":" 2\\n氐土貉 1.7m/s 女巫","color":"black"},{"text":"　","color":"#333333"},{"text":" 3 \\n奎木狼 1.7m/s 苦力怕 4\\n尾火虎 1.7m/s 恶魂","color":"black"},{"text":"　","color":"#333333"},{"text":" 5 ","color":"black"}]',\
    '["",{"text":"名称   代号\\n娄金狗 guardian\\n箕水豹 lightning\\n氐土貉 shield_buster\\n奎木狼 tomahawk\\n尾火虎 juggernaut\\n\\n"},{"text":"4.2 融合导弹","color":"dark_green"},{"text":"（5）","color":"gray"},{"text":"\\n\\n以下5种导弹为本改版原创，可以通过两种基础导弹的怪物蛋合成得到。\\n ","color":"black"}]',\
    '["",{"text":"名称 长宽高"},{"text":"　","color":"#333333"},{"text":" 弹药量\\n沙皇 11x3x3 ","color":"black"},{"text":"1+6","color":"dark_red"},{"text":"\\n柄雷 13x3x3 ","color":"black"},{"text":"4+6","color":"red"},{"text":"\\n炎狱 11x2x2 ","color":"black"},{"text":"11","color":"gold"},{"text":"\\n东风 09x3x3 ","color":"black"},{"text":"25","color":"red"},{"text":"\\n匕首 10x2x2 ","color":"black"},{"text":"11","color":"gold"},{"text":"\\n\\n名称 移速","color":"black"},{"text":"　","color":"#333333"},{"text":"  怪物蛋","color":"black"},{"text":"　","color":"#333333"},{"text":" No\\n沙皇 1.7m/s 铁傀儡","color":"black"},{"text":"　","color":"#333333"},{"text":" 11 \\n柄雷 1.7m/s 僵尸猪灵 12 \\n炎狱 1.7m/s 岩浆怪","color":"black"},{"text":"　","color":"#333333"},{"text":" 13\\n东风 ","color":"black"},{"text":"3.3m/s","color":"red"},{"text":" 蜘蛛","color":"black"},{"text":"　　","color":"#333333"},{"text":" 14\\n匕首 ","color":"black"},{"text":"3.3m/s","color":"red"},{"text":" 洞穴蜘蛛 15 ","color":"black"}]',\
    '["",{"text":"名称 代号\\n沙皇 tsar\\n柄雷 stielhandgranate\\n炎狱 hellfire\\n东风 dongfeng\\n匕首 kinzhal\\n\\n注：加号后的数字代表"},{"text":"TNT矿车\\n\\n","color":"dark_red"},{"text":"4.3 特种导弹","color":"dark_green"},{"text":"（3）","color":"gray"},{"text":"\\n\\n以下3种导弹为本改版原创，行使特殊职能。\\n ","color":"black"}]',\
    '[{"text": "名称　 长宽高　 弹药量\\n"}, {"text": "天启", "color": "light_purple"}, {"text": "　 11x2x5 ", "color": "black"}, {"text": "6+5", "color": "red"}, {"text": "\\n", "color": "black"}, {"text": "仪凤", "color": "light_purple"}, {"text": "　 15x2x5 ", "color": "black"}, {"text": "13", "color": "gold"}, {"text": "\\n", "color": "black"}, {"text": "铺路机", "color": "light_purple"}, {"text": " 14x3x3 ", "color": "black"}, {"text": "21", "color": "red"}, {"text": "\\n\\n名称　 移速　  怪物蛋　\\n", "color": "black"}, {"text": "天启", "color": "light_purple"}, {"text": "　 1.7m/s 凋零骷髅\\n", "color": "black"}, {"text": "仪凤", "color": "light_purple"}, {"text": "　 1.3m/s 鹦鹉　　\\n", "color": "black"}, {"text": "铺路机", "color": "light_purple"}, {"text": " ", "color": "black"}, {"text": "0.5m/s", "color": "dark_aqua"}, {"text": " 鱿鱼\\n", "color": "black"}]',\
    '[{"text": "名称　 No\\n"}, {"text": "天启", "color": "light_purple"}, {"text": "　 21\\n", "color": "black"}, {"text": "仪凤", "color": "light_purple"}, {"text": "　 22\\n", "color": "black"}, {"text": "铺路机", "color": "light_purple"}, {"text": " 25\\n\\n名称　 代号\\n", "color": "black"}, {"text": "天启", "color": "light_purple"}, {"text": "　 apocalypse\\n", "color": "black"}, {"text": "仪凤", "color": "light_purple"}, {"text": "　 phoenix\\n", "color": "black"}, {"text": "铺路机", "color": "light_purple"}, {"text": " paver", "color": "black"}]',\
    '["",{"text":"5 指令集","bold":true},{"text":"\\n\\n","color":"black"},{"text":"5.1 功能触发指令","color":"dark_green"},{"text":"\\n\\n使用指令\\n/","color":"black"},{"text":"trigger","color":"light_purple"},{"text":" 功能名","color":"dark_aqua"},{"text":"\\n不同的功能对应如下表\\n\\n功能名   实现功能\\n","color":"black"},{"text":"menu","color":"dark_aqua"},{"text":"  调出菜单\\n","color":"black"},{"text":"start","color":"dark_aqua"},{"text":"  申请开始游戏\\n","color":"black"},{"text":"stop","color":"dark_aqua"},{"text":"在游戏进行时强制停止\\n","color":"black"},{"text":"settings","color":"dark_aqua"},{"text":"查看并修改游戏设置\\n","color":"black"}]',\
    '[{"text": "功能名   实现功能\\n","color": "black"},{"text":"team","color":"dark_aqua"},{"text":" 查看并修改组队设置\\n","color":"black"},{"text":"help","color":"dark_aqua"},{"text":"   获取帮助手册\\n","color":"black"},{"text":"ready","color":"dark_aqua"},{"text":"   完成选卡\\n\\n","color":"black"},{"text":"5.2 手动组队指令","color":"dark_green"},{"text":"\\n\\n手动加入绿队\\n/","color":"black"},{"text":"trigger","color":"light_purple"},{"text":" join","color":"dark_aqua"},{"text":" set","color":"dark_blue"},{"text":" 1","color":"dark_green"},{"text":"\\n手动加入黄队\\n/","color":"black"},{"text":"trigger","color":"light_purple"},{"text":" join","color":"dark_aqua"},{"text":" set","color":"dark_blue"},{"text":" 2","color":"dark_green"}]',\
    '["",{"text":"5.3 手动更改规则指令","color":"dark_green"},{"text":"\\n\\n使用指令\\n/","color":"black"},{"text":"trigger","color":"light_purple"},{"text":" set.规则名","color":"dark_aqua"},{"text":" set","color":"dark_blue"},{"text":" 值","color":"dark_green"},{"text":"\\n不同的","color":"black"},{"text":"规则名","color":"dark_aqua"},{"text":"和","color":"black"},{"text":"值","color":"dark_green"},{"text":"的对应如下\\n\\n以下二元规则，值为","color":"black"},{"text":"1","color":"dark_green"},{"text":"时设置为","color":"black"},{"text":"禁用","color":"dark_red"},{"text":"，为","color":"black"},{"text":"2","color":"dark_green"},{"text":"时设置为","color":"black"},{"text":"启用","color":"dark_green"},{"text":"。特别地，对于部署位置，“","color":"black"},{"text":"启用","color":"dark_green"},{"text":"”意味着“","color":"black"},{"text":"仅可在平台部署","color":"dark_red"},{"text":"”。","color":"black"}]',\
    '["",{"text":"规则　　 规则名\\n"},{"text":"原版规则","color":"gold"},{"text":" origin","color":"dark_aqua"},{"text":" \\n","color":"black"},{"text":"随机组队","color":"gold"},{"text":" randomTeaming","color":"dark_aqua"},{"text":"\\n","color":"black"},{"text":"破坏方块","color":"gold"},{"text":" blockBreaking","color":"dark_aqua"},{"text":" \\n","color":"black"},{"text":"火球防御","color":"gold"},{"text":" fireballShield","color":"dark_aqua"},{"text":" \\n","color":"black"},{"text":"死亡不掉落","color":"gold"},{"text":" keepInventory","color":"dark_aqua"},{"text":" \\n","color":"black"},{"text":"道具上限","color":"gold"},{"text":" itemCap","color":"dark_aqua"},{"text":" \\n","color":"black"},{"text":"防御道具","color":"gold"},{"text":" defensiveItems","color":"dark_aqua"},{"text":" \\n","color":"black"},{"text":"部署位置","color":"gold"},{"text":" launchAreaRistriction","color":"dark_aqua"}]',\
    '["",{"text":"以下数值规则，“"},{"text":"值","color":"dark_green"},{"text":"”等于欲设置的数值，在合法取值范围内即可设置成功。\\n\\n规则　　 规则名\\n","color":"black"},{"text":"平台距离 distance\\n平台厚度 thickness\\n箭矢数量 clipSize\\n消退时间 decayTime\\n补给时间 resupplyTime","color":"dark_aqua"}]',\
    '["",{"text":"规则　　 合法范围\\n"},{"text":"平台距离","color":"dark_aqua"},{"text":" [1,127]","color":"dark_green"},{"text":"\\n","color":"black"},{"text":"平台厚度","color":"dark_aqua"},{"text":" [1,10]","color":"dark_green"},{"text":"\\n","color":"black"},{"text":"箭矢数量","color":"dark_aqua"},{"text":" [1,10]","color":"dark_green"},{"text":"\\n","color":"black"},{"text":"消退时间","color":"dark_aqua"},{"text":" [1,65535]","color":"dark_green"},{"text":"\\n","color":"black"},{"text":"补给时间","color":"dark_aqua"},{"text":" [1,2047]","color":"dark_green"},{"text": "\\n注：将消退时间设为65536及以上会将消退禁用","color": "gray"},{"text":"\\n规则　　 单位\\n","color":"black"},{"text":"平台距离","color":"dark_aqua"},{"text":" (x2+1)格\\n","color":"black"},{"text":"平台厚度","color":"dark_aqua"},{"text":" x3格\\n","color":"black"},{"text":"箭矢数量","color":"dark_aqua"},{"text":" 支\\n","color":"black"},{"text":"消退时间","color":"dark_aqua"},{"text":" x0.05秒\\n","color":"black"},{"text":"补给时间","color":"dark_aqua"},{"text":" x0.05秒","color":"black"}]',\
    '["",{"text":"以下多元规则，值和对应的条目如下表，除表中列出的值皆为非法。\\n\\n规则　　 规则名\\n"},{"text":"平台材料","color":"light_purple"},{"text":" material","color":"dark_aqua"},{"text":"\\n","color":"black"},{"text":"游戏模式","color":"light_purple"},{"text":" mode","color":"dark_aqua"},{"text":"\\n","color":"black"},{"text":"行动增益","color":"light_purple"},{"text":" boots","color":"dark_aqua"}]',\
    '["",{"text":"平台材料","color":"light_purple"},{"text":"\\n","color":"black"},{"text":"1=","color":"dark_green"},{"text":"玻璃 ","color":"black"},{"text":"2=","color":"dark_green"},{"text":"羊毛 ","color":"black"},{"text":"3=","color":"dark_green"},{"text":"带釉陶瓦 ","color":"black"},{"text":"4=","color":"dark_green"},{"text":"混凝土 ","color":"black"},{"text":"5=","color":"dark_green"},{"text":"陶瓦\\n","color":"black"},{"text":"游戏模式","color":"light_purple"},{"text":"\\n","color":"black"},{"text":"1=","color":"dark_green"},{"text":"普通模式 ","color":"black"},{"text":"2=","color":"dark_green"},{"text":"分钟模式 ","color":"black"},{"text":"4=","color":"dark_green"},{"text":"皇室模式\\n","color":"black"},{"text":"行动增益","color":"light_purple"},{"text":"\\n","color":"black"},{"text":"1=","color":"dark_green"},{"text":"普通移速 ","color":"black"},{"text":"2=","color":"dark_green"},{"text":"神行太保 ","color":"black"},{"text":"3=","color":"dark_green"},{"text":"齐天大圣","color":"black"},{"text": "\\n注：对于非数值规则，通过trigger设置的值实际上比系统内存储的值多1，如系统内普通模式的代码为0。","color": "gray"}]'\
    ],title:"游戏帮助",author:CZM}]